"""Regenerates js/fonts.js: the card fonts as base64 @font-face rules.

Embedding the fonts lets the app run from file:// and gives html-to-image
the exact same fonts for exports as the on-screen preview.
Usage: python3 tools/build-fonts.py   (run from the id-card-generator folder)
"""
import base64, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS = [("Montserrat", "montserrat", w) for w in (400, 500, 600, 700)] + \
        [("Open Sans", "open-sans", w) for w in (400, 500)]

rules = []
for family, slug, weight in FONTS:
    data = (ROOT / "tools" / "fonts" / f"{slug}-latin-{weight}-normal.woff2").read_bytes()
    b64 = base64.b64encode(data).decode()
    rules.append(f"@font-face{{font-family:'{family}';font-style:normal;font-weight:{weight};"
                 f"font-display:block;src:url(data:font/woff2;base64,{b64}) format('woff2');}}")
css = "\n".join(rules)
(ROOT / "js" / "fonts.js").write_text(
    "// Generated by tools/build-fonts.py - do not edit by hand.\n"
    "window.IDCARD_FONT_CSS = " + repr(css).replace("\\n", "\\n") + ";\n")
print("wrote js/fonts.js", len(css) // 1024, "KB")
